In [2]:
import pandas as pd
import numpy as np

In [4]:
patients = pd.read_csv("patients.csv")
encounters = pd.read_csv("encounters.csv")
procedures = pd.read_csv("procedures.csv")
payers = pd.read_csv("payers.csv")
organizations = pd.read_csv("organizations.csv")

In [10]:
datasets = {
    "patients": patients,
    "encounters": encounters,
    "procedures": procedures,
    "payers": payers,
    "organizations": organizations
}

for name, df in datasets.items():
    print(f"\n{name.upper()}")
    print("-"*50)
    print("Shape:", df.shape)
    print("Missing Values:")
    print(df.isnull().sum())
    print("\nDuplicates:", df.duplicated().sum())

PATIENTS
--------------------------------------------------
Shape: (974, 18)
Missing Values:
Id              0
BIRTHDATE       0
DEATHDATE     820
PREFIX          0
FIRST           0
LAST            0
MARITAL         1
RACE            0
ETHNICITY       0
GENDER          0
BIRTHPLACE      0
ADDRESS         0
CITY            0
STATE           0
COUNTY          0
ZIP           142
LAT             0
LON             0
dtype: int64

Duplicates: 0

ENCOUNTERS
--------------------------------------------------
Shape: (27891, 14)
Missing Values:
Id                         0
START                      0
STOP                       0
PATIENT                    0
ORGANIZATION               0
PAYER                      0
ENCOUNTERCLASS             0
CODE                       0
DESCRIPTION                0
BASE_ENCOUNTER_COST        0
TOTAL_CLAIM_COST           0
PAYER_COVERAGE             0
REASONCODE             19541
REASONDESCRIPTION      19541
dtype: int64

Duplicates: 0

PROCEDURES
--------------------------------------------------
Shape: (47701, 9)
Missing Values:
START                    0
STOP                     0
PATIENT                  0
ENCOUNTER                0
CODE                     0
DESCRIPTION              0
BASE_COST                0
REASONCODE           36945
REASONDESCRIPTION    36945
dtype: int64

Duplicates: 0

PAYERS
--------------------------------------------------
Shape: (10, 7)
Missing Values:
Id                     0
NAME                   0
ADDRESS                1
CITY                   1
STATE_HEADQUARTERED    1
ZIP                    1
PHONE                  1
dtype: int64

Duplicates: 0

ORGANIZATIONS
--------------------------------------------------
Shape: (1, 8)
Missing Values:
Id         0
NAME       0
ADDRESS    0
CITY       0
STATE      0
ZIP        0
LAT        0
LON        0
dtype: int64

Duplicates: 0

In [12]:
patients['MARITAL'] = patients['MARITAL'].fillna('Unknown')

In [14]:
patients['BIRTHDATE'] = pd.to_datetime(patients['BIRTHDATE'])
patients['DEATHDATE'] = pd.to_datetime(patients['DEATHDATE'])

In [16]:
from datetime import datetime

today = pd.Timestamp.today()

patients['AGE'] = (
    (today - patients['BIRTHDATE']).dt.days // 365
)

In [18]:
patients['ZIP'] = patients['ZIP'].fillna('Unknown')

In [20]:
encounters.isnull().sum()

Id                         0
START                      0
STOP                       0
PATIENT                    0
ORGANIZATION               0
PAYER                      0
ENCOUNTERCLASS             0
CODE                       0
DESCRIPTION                0
BASE_ENCOUNTER_COST        0
TOTAL_CLAIM_COST           0
PAYER_COVERAGE             0
REASONCODE             19541
REASONDESCRIPTION      19541
dtype: int64

In [22]:
patients.isnull().sum()

Id              0
BIRTHDATE       0
DEATHDATE     820
PREFIX          0
FIRST           0
LAST            0
MARITAL         0
RACE            0
ETHNICITY       0
GENDER          0
BIRTHPLACE      0
ADDRESS         0
CITY            0
STATE           0
COUNTY          0
ZIP             0
LAT             0
LON             0
AGE             0
dtype: int64

In [24]:
encounters['REASONCODE'] = encounters['REASONCODE'].fillna('Unknown')
encounters['REASONDESCRIPTION'] = encounters['REASONDESCRIPTION'].fillna('Unknown')

In [26]:
encounters['START'] = pd.to_datetime(encounters['START'])
encounters['STOP'] = pd.to_datetime(encounters['STOP'])

In [27]:
encounters['LENGTH_OF_STAY_DAYS'] = (
    encounters['STOP'] - encounters['START']
).dt.total_seconds() / (24 * 60 * 60)

In [28]:
encounters[['START','STOP','LENGTH_OF_STAY_DAYS']].head()

                      START                      STOP  LENGTH_OF_STAY_DAYS
0 2011-01-02 09:26:36+00:00 2011-01-02 12:58:36+00:00             0.147222
1 2011-01-03 05:44:39+00:00 2011-01-03 06:01:42+00:00             0.011840
2 2011-01-03 14:32:11+00:00 2011-01-03 14:47:11+00:00             0.010417
3 2011-01-03 16:24:45+00:00 2011-01-03 16:39:45+00:00             0.010417
4 2011-01-03 17:36:53+00:00 2011-01-03 17:51:53+00:00             0.010417

In [29]:
print("Total Encounters:", len(encounters))

print("Average Stay:",
      round(encounters['LENGTH_OF_STAY_DAYS'].mean(),2),
      "days")

print("Average Claim Cost:",
      round(encounters['TOTAL_CLAIM_COST'].mean(),2))

print("Average Coverage:",
      round(encounters['PAYER_COVERAGE'].mean(),2))

Total Encounters: 27891
Average Stay: 0.3 days
Average Claim Cost: 3639.68
Average Coverage: 1114.97

In [30]:
procedures.isnull().sum()

START                    0
STOP                     0
PATIENT                  0
ENCOUNTER                0
CODE                     0
DESCRIPTION              0
BASE_COST                0
REASONCODE           36945
REASONDESCRIPTION    36945
dtype: int64

In [32]:
procedures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47701 entries, 0 to 47700
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   START              47701 non-null  object
 1   STOP               47701 non-null  object
 2   PATIENT            47701 non-null  object
 3   ENCOUNTER          47701 non-null  object
 4   CODE               47701 non-null  int64
 5   DESCRIPTION        47701 non-null  object
 6   BASE_COST          47701 non-null  int64
 7   REASONCODE         10756 non-null  float64
 8   REASONDESCRIPTION  10756 non-null  object
dtypes: float64(1), int64(2), object(6)
memory usage: 3.3+ MB

In [33]:
procedures['REASONCODE'] = procedures['REASONCODE'].fillna('Unknown')
procedures['REASONDESCRIPTION'] = procedures['REASONDESCRIPTION'].fillna('Unknown')

In [34]:
procedures.isnull().sum()

START                0
STOP                 0
PATIENT              0
ENCOUNTER            0
CODE                 0
DESCRIPTION          0
BASE_COST            0
REASONCODE           0
REASONDESCRIPTION    0
dtype: int64

In [35]:
print("Duplicates:", procedures.duplicated().sum())

Duplicates: 0

In [37]:
payers.info()
payers.head()
payers.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   10 non-null     object
 1   NAME                 10 non-null     object
 2   ADDRESS              9 non-null      object
 3   CITY                 9 non-null      object
 4   STATE_HEADQUARTERED  9 non-null      object
 5   ZIP                  9 non-null      float64
 6   PHONE                9 non-null      object
dtypes: float64(1), object(6)
memory usage: 692.0+ bytes

Id                     0
NAME                   0
ADDRESS                1
CITY                   1
STATE_HEADQUARTERED    1
ZIP                    1
PHONE                  1
dtype: int64

In [39]:
organizations.info()
organizations.head()
organizations.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Id       1 non-null      object
 1   NAME     1 non-null      object
 2   ADDRESS  1 non-null      object
 3   CITY     1 non-null      object
 4   STATE    1 non-null      object
 5   ZIP      1 non-null      int64
 6   LAT      1 non-null      float64
 7   LON      1 non-null      float64
dtypes: float64(2), int64(1), object(5)
memory usage: 196.0+ bytes

Id         0
NAME       0
ADDRESS    0
CITY       0
STATE      0
ZIP        0
LAT        0
LON        0
dtype: int64

In [40]:
data_dictionary.head(20)

NameError: name 'data_dictionary' is not defined

In [42]:
data_dictionary = pd.read_csv("data_dictionary.csv")
data_dictionary.head(20)

,Table,Field,Description
0,encounters,NaN,Patient encounter data
1,encounters,Id,Primary Key. Unique Identifier of the encounter.
2,encounters,Start,The date and time (iso8601 UTC Date (yyyy-MM-d...
3,encounters,Stop,The date and time (iso8601 UTC Date (yyyy-MM-d...
4,encounters,Patient,Foreign key to the Patient.
5,encounters,Organization,Foreign key to the Organization.
6,encounters,Payer,Foreign key to the Payer.
7,encounters,EncounterClass,"The class of the encounter, such as ambulatory..."
8,encounters,Code,Encounter code from SNOMED-CT
9,encounters,Description,Description of the type of encounter.
10,encounters,Base_Encounter_Cost,"The base cost of the encounter, not including ..."
11,encounters,Total_Claim_Cost,"The total cost of the encounter, including all..."
12,encounters,Payer_Coverage,The amount of cost covered by the Payer.
13,encounters,ReasonCode,"Diagnosis code from SNOMED-CT, only if this en..."
14,encounters,ReasonDescription,Description of the reason code.
15,organizations,NaN,Hospital details
16,organizations,Id,Primary key of the Organization.
17,organizations,Name,Name of the Organization.
18,organizations,Address,Organization's street address without commas o...
19,organizations,City,Street address city.

In [44]:
patients.to_csv("patients_clean.csv", index=False)
encounters.to_csv("encounters_clean.csv", index=False)
procedures.to_csv("procedures_clean.csv", index=False)
payers.to_csv("payers_clean.csv", index=False)
organizations.to_csv("organizations_clean.csv", index=False)

In [45]:
patients['AGE'].describe()

count    974.000000
mean      73.732033
std       20.489063
min       34.000000
25%       56.000000
50%       76.000000
75%       93.000000
max      104.000000
Name: AGE, dtype: float64

In [47]:
encounters['ENCOUNTERCLASS'].value_counts()

ENCOUNTERCLASS
ambulatory    12537
outpatient     6300
urgentcare     3666
emergency      2322
wellness       1931
inpatient      1135
Name: count, dtype: int64

In [48]:
encounters['TOTAL_CLAIM_COST'].describe()

count     27891.000000
mean       3639.682174
std        9205.595748
min           0.000000
25%         142.580000
50%         278.580000
75%        1412.530000
max      641882.700000
Name: TOTAL_CLAIM_COST, dtype: float64

In [49]:
procedures.isnull().sum()

START                0
STOP                 0
PATIENT              0
ENCOUNTER            0
CODE                 0
DESCRIPTION          0
BASE_COST            0
REASONCODE           0
REASONDESCRIPTION    0
dtype: int64

In [50]:
procedures['DESCRIPTION'].value_counts().head(10)

DESCRIPTION
Assessment of health and social care needs (procedure)                                4596
Hospice care (regime/therapy)                                                         4098
Depression screening using Patient Health Questionnaire Two-Item score (procedure)    3614
Depression screening (procedure)                                                      3614
Assessment of substance use (procedure)                                               2906
Renal dialysis (procedure)                                                            2746
Assessment using Morse Fall Scale (procedure)                                         2422
Assessment of anxiety (procedure)                                                     2288
Medication Reconciliation (procedure)                                                 2284
Screening for drug abuse (procedure)                                                  1484
Name: count, dtype: int64

In [51]:
patients['GENDER'].value_counts()

GENDER
M    494
F    480
Name: count, dtype: int64

In [52]:
patients['RACE'].value_counts()

RACE
white       680
black       163
asian        91
other        16
hawaiian     13
native       11
Name: count, dtype: int64

In [53]:
encounters['YEAR'] = encounters['START'].dt.year

yearly_admissions = (
    encounters.groupby('YEAR')['Id']
    .count()
    .reset_index(name='Admissions')
)

yearly_admissions

    YEAR  Admissions
0   2011        1336
1   2012        2106
2   2013        2495
3   2014        3885
4   2015        2469
5   2016        2451
6   2017        2360
7   2018        2292
8   2019        2228
9   2020        2519
10  2021        3530
11  2022         220

In [54]:
encounters.groupby('ENCOUNTERCLASS')['TOTAL_CLAIM_COST'] \
.mean() \
.sort_values(ascending=False)

ENCOUNTERCLASS
inpatient     7761.351841
urgentcare    6369.162564
emergency     4629.651822
wellness      4260.710373
ambulatory    2894.108705
outpatient    2237.296368
Name: TOTAL_CLAIM_COST, dtype: float64

In [55]:
encounters.groupby('PAYER')[
    ['TOTAL_CLAIM_COST','PAYER_COVERAGE']
].sum().sort_values(
    by='PAYER_COVERAGE',
    ascending=False
)

                                      TOTAL_CLAIM_COST  PAYER_COVERAGE
PAYER
7caa7254-5050-3b5e-9eae-bd5ea30e809c       24647228.89     19215691.37
7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a        8954131.02      8417973.72
6e2f1a2d-27bd-3701-8d08-dae202c58632        3002166.01      2074496.34
b3221cfc-24fb-339e-823d-bc4136cbc4ed        1546925.99      1380705.87
5059a55e-5d6e-34d1-b6cb-d83d16e57bcf        2563507.98         3937.32
d47b3510-2895-3b70-9897-342d681c769d        3543921.36         1953.86
4d71f845-a6a9-3c39-b242-14d25ef86a8d        2589956.10         1780.16
047f6ec3-6215-35eb-9608-f9dda363a44c        2424532.96          968.35
42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a        2982715.05            0.00
b1c428d6-4f07-31e0-90f0-68ffa6ff8c76       49259290.16            0.00

In [56]:
patients.columns = patients.columns.str.lower()
encounters.columns = encounters.columns.str.lower()
procedures.columns = procedures.columns.str.lower()
payers.columns = payers.columns.str.lower()
organizations.columns = organizations.columns.str.lower()

In [58]:
print(patients.columns)
print(encounters.columns)

Index(['id', 'birthdate', 'deathdate', 'prefix', 'first', 'last', 'marital',
       'race', 'ethnicity', 'gender', 'birthplace', 'address', 'city', 'state',
       'county', 'zip', 'lat', 'lon', 'age'],
      dtype='object')
Index(['id', 'start', 'stop', 'patient', 'organization', 'payer',
       'encounterclass', 'code', 'description', 'base_encounter_cost',
       'total_claim_cost', 'payer_coverage', 'reasoncode', 'reasondescription',
       'length_of_stay_days', 'year'],
      dtype='object')

In [59]:
patients.to_csv("patients_clean.csv", index=False)
encounters.to_csv("encounters_clean.csv", index=False)
procedures.to_csv("procedures_clean.csv", index=False)
payers.to_csv("payers_clean.csv", index=False)
organizations.to_csv("organizations_clean.csv", index=False)

In [61]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\gaurav choubey\anaconda3\lib\site-packages (1.4.39)
Requirement already satisfied: pymysql in c:\users\gaurav choubey\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\gaurav choubey\anaconda3\lib\site-packages (from sqlalchemy) (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [62]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:gaushi@localhost:3306"
)

with engine.connect() as conn:
    conn.exec_driver_sql("CREATE DATABASE IF NOT EXISTS hospital_db")

print("Database created successfully!")

Database created successfully!

In [63]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:gaushi@localhost:3306/hospital_db"
)

print("Connected Successfully!")

Connected Successfully!

In [64]:
patients.to_sql("patients", engine, if_exists="replace", index=False)

974

In [65]:
encounters.to_sql("encounters", engine, if_exists="replace", index=False)
procedures.to_sql("procedures", engine, if_exists="replace", index=False)
payers.to_sql("payers", engine, if_exists="replace", index=False)
organizations.to_sql("organizations", engine, if_exists="replace", index=False)

print("All tables uploaded!")

All tables uploaded!